//Represents an Customer in the Restaraunt DB
//All methods auto-generated by Eclipse
public class PR_CUSTOMERS {
	
	private int customerid;
	private String phonenum; 
	private String name;
	private String email;

	
	public PR_CUSTOMERS(int customerid, String phonenum, String name, String email) {
		super();
		this.customerid = customerid;
		this.phonenum = phonenum;
		this.name = name;
		this.email = email;
 
	}

	public int getcustomerid() {
		return customerid;
	}

	public void setcustomerid(int customerid) {
		this.customerid = customerid;
	}

	public String getphonenum() {
		return phonenum;
	}

	public void setphonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	public String getname() {
		return name;
	}

	public void setname(String name) {
		this.name = name;
	}

	public String getemail() {
		return email;
	}

	public void setemail(String email) {
		this.email = email;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PR_CUSTOMERS other = (PR_CUSTOMERS) obj;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PR_CUSTOMERS [customerid=" + customerid + ", phonenum=" + phonenum + ", name=" + name + ", email=" + email + "]";
	}
	
	
}
